version: "3.1"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: tatsujin-sql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/home/sql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data: {}
