version: "3.1"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: tatsujin-sql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/home/sql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tatsujin

volumes:
  db_data: {}
